version: '3'

services:
  app:
    build:
      context: ./app
    ports:
      - "3000:3000"
    depends_on:
      - mysql
    command: dockerize -wait tcp://mysql:3306 -timeout 30s npm start

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./mysql_data:/var/lib/mysql
    restart: always

  nginx:
    build:
      context: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - app

